# Generated by Django 4.2.16 on 2024-11-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation_backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedmodel",
            name="image",
            field=models.URLField(
                default="https://www.hindustantimes.com/feeds/rss/world-news/rssfeed.xml"
            ),
        ),
        migrations.AlterField(
            model_name="feedmodel", name="link", field=models.URLField(unique=True),
        ),
    ]
